In [1]:
import numpy as np

In [3]:
# The basics
# creating an array and checking it's basic features.
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
(5,)
5
1
int64
<class 'numpy.ndarray'>


In [43]:
# using functions to create an arry
array = np.arange(-5, 5, 2)
print(array)

zeros = np.zeros((3,3))
print(zeros)

ones = np.ones((3,3))
print(ones)

identity = np.identity(3)
print(identity)

linspace = np.linspace(0,10, 5)
print(linspace)

a = np.random.randint(1, 10, size=(5,5))
print(a)

b = np.random.rand(5,5)
print(b)

c = np.random.random_sample(array.shape)
print(c)

[-5 -3 -1  1  3]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0.   2.5  5.   7.5 10. ]
[[6 4 4 4 1]
 [6 1 7 3 4]
 [1 1 8 3 7]
 [2 2 4 4 6]
 [8 1 9 3 5]]
[[0.8473779  0.43225299 0.90624181 0.10044228 0.04027874]
 [0.1577938  0.63689964 0.28946342 0.3862667  0.94805746]
 [0.39963841 0.57488759 0.80444907 0.17761318 0.67296946]
 [0.22942708 0.45778866 0.35196292 0.39253415 0.36534943]
 [0.32119441 0.85557258 0.18640821 0.5723081  0.63098334]]
[0.84496128 0.35111496 0.86710593 0.9252786  0.12684984]


In [19]:
# using alike function
array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10],
                  [11,12,13,14,15]
                  ])
alikearray = np.full_like(array, 5)
print(alikearray)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [25]:
# Accesing elements 
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]
                  ])
print(a)
print(a[0])
print(a[2,3])
a[2,3] = 999
print(a[2,3])
print(a)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[1 2 3 4 5]
14
999
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 999  15]]


In [33]:
# combinening ndarrays
zeros = np.zeros((3,3))
ones = np.ones((3,3))
zeros_ones = np.concatenate((zeros, ones), axis = 0)
print(zeros_ones)

zeros = np.zeros((3,3))
ones = np.ones((3,3))
zeros_ones = np.concatenate((zeros, ones), axis = 1)
print(zeros_ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [58]:
# reshaping the array

a = np.random.randint(1, 10, size=(8,8))
print(a)

b = a.reshape(2,32)
print(b)

c = a.reshape(16,4)
print(c)

d = a.reshape(4,16)
print(d)

e = a.reshape(-1)
print(e)
 
f = a.reshape(4, -1)     #important -1 means it takes own axis that is compatable.
print(f)

g = a.reshape(-1, 4)
print(g)

[[8 4 9 9 4 7 1 9]
 [9 7 1 1 3 8 7 3]
 [9 8 8 9 4 1 8 3]
 [3 8 6 6 5 8 5 5]
 [9 9 4 3 6 3 8 7]
 [2 6 3 1 2 3 2 5]
 [6 5 3 9 3 6 1 7]
 [8 2 5 5 4 5 3 1]]
[[8 4 9 9 4 7 1 9 9 7 1 1 3 8 7 3 9 8 8 9 4 1 8 3 3 8 6 6 5 8 5 5]
 [9 9 4 3 6 3 8 7 2 6 3 1 2 3 2 5 6 5 3 9 3 6 1 7 8 2 5 5 4 5 3 1]]
[[8 4 9 9]
 [4 7 1 9]
 [9 7 1 1]
 [3 8 7 3]
 [9 8 8 9]
 [4 1 8 3]
 [3 8 6 6]
 [5 8 5 5]
 [9 9 4 3]
 [6 3 8 7]
 [2 6 3 1]
 [2 3 2 5]
 [6 5 3 9]
 [3 6 1 7]
 [8 2 5 5]
 [4 5 3 1]]
[[8 4 9 9 4 7 1 9 9 7 1 1 3 8 7 3]
 [9 8 8 9 4 1 8 3 3 8 6 6 5 8 5 5]
 [9 9 4 3 6 3 8 7 2 6 3 1 2 3 2 5]
 [6 5 3 9 3 6 1 7 8 2 5 5 4 5 3 1]]
[8 4 9 9 4 7 1 9 9 7 1 1 3 8 7 3 9 8 8 9 4 1 8 3 3 8 6 6 5 8 5 5 9 9 4 3 6
 3 8 7 2 6 3 1 2 3 2 5 6 5 3 9 3 6 1 7 8 2 5 5 4 5 3 1]
[[8 4 9 9 4 7 1 9 9 7 1 1 3 8 7 3]
 [9 8 8 9 4 1 8 3 3 8 6 6 5 8 5 5]
 [9 9 4 3 6 3 8 7 2 6 3 1 2 3 2 5]
 [6 5 3 9 3 6 1 7 8 2 5 5 4 5 3 1]]
[[8 4 9 9]
 [4 7 1 9]
 [9 7 1 1]
 [3 8 7 3]
 [9 8 8 9]
 [4 1 8 3]
 [3 8 6 6]
 [5 8 5 5]
 [9 9 4 3]
 [6 3 8 7]
 [2 6 3 1]
 

In [62]:
# convert a 1D array into a 2D array (how to add a new axis to an array)
a = np.arange(10)
print(a.shape)
print(a)

b = a[np.newaxis, :]
print(b.shape)
print(b)

(10,)
[0 1 2 3 4 5 6 7 8 9]
(1, 10)
[[0 1 2 3 4 5 6 7 8 9]]


In [90]:
 # indexing and slicing
a = np.random.randint(1, 10, size=(8,8))
print(a)
print(np.unique(a))

print(a[0])     #first row
print(a[0,:])   #first row
print(a[:,0])   #first column

print(a[2, 3:6]) # 3rd row, from col-3 to col-5
print(a[2:6, 1:4])  # from row-3 to row-5 and col-2 to col-3
a[2:6, 1:4]  = 0 
print(a[:])

print(a[a<5])    # all the elements in tha array less than 5

b = a < 5        # marks true if conditon is  satisfied else flase at that point
print(b)

a[b] = 999     # where ever you find element less that 5 replace with 999 "This is called masking"
print(a)

print(np.unique(a))


[[6 9 7 2 7 8 6 9]
 [6 5 3 8 4 9 6 6]
 [9 6 8 7 5 5 2 8]
 [5 9 7 5 7 6 9 1]
 [7 7 8 1 5 8 9 5]
 [9 1 1 3 3 6 2 7]
 [6 6 6 3 4 1 9 5]
 [6 3 4 1 7 7 9 2]]
[1 2 3 4 5 6 7 8 9]
[6 9 7 2 7 8 6 9]
[6 9 7 2 7 8 6 9]
[6 6 9 5 7 9 6 6]
[7 5 5]
[[6 8 7]
 [9 7 5]
 [7 8 1]
 [1 1 3]]
[[6 9 7 2 7 8 6 9]
 [6 5 3 8 4 9 6 6]
 [9 0 0 0 5 5 2 8]
 [5 0 0 0 7 6 9 1]
 [7 0 0 0 5 8 9 5]
 [9 0 0 0 3 6 2 7]
 [6 6 6 3 4 1 9 5]
 [6 3 4 1 7 7 9 2]]
[2 3 4 0 0 0 2 0 0 0 1 0 0 0 0 0 0 3 2 3 4 1 3 4 1 2]
[[False False False  True False False False False]
 [False False  True False  True False False False]
 [False  True  True  True False False  True False]
 [False  True  True  True False False False  True]
 [False  True  True  True False False False False]
 [False  True  True  True  True False  True False]
 [False False False  True  True  True False False]
 [False  True  True  True False False False  True]]
[[  6   9   7 999   7   8   6   9]
 [  6   5 999   8 999   9   6   6]
 [  9 999 999 999   5   5 999   8]
 [  5 9

In [81]:
# array opertations
a  = np.arange(25).reshape((5,5))
print(a)

b = a.copy()

print(a + 5)
print(a - 5)
print(a * 5)
print(a / 5)                 # This is called "Broadcasting". In simple word opertaions are done element wise
print(a ** 5)
print(a // 5)
print(a % 5)

print(a+b)
print(a-b)                    
print(a*b)
print(a/b)
print(a ** b)
print(a // b)              # The error below says we have divison by zero. But the operation gets performed
print(a % b)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[-5 -4 -3 -2 -1]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[  0   5  10  15  20]
 [ 25  30  35  40  45]
 [ 50  55  60  65  70]
 [ 75  80  85  90  95]
 [100 105 110 115 120]]
[[0.  0.2 0.4 0.6 0.8]
 [1.  1.2 1.4 1.6 1.8]
 [2.  2.2 2.4 2.6 2.8]
 [3.  3.2 3.4 3.6 3.8]
 [4.  4.2 4.4 4.6 4.8]]
[[      0       1      32     243    1024]
 [   3125    7776   16807   32768   59049]
 [ 100000  161051  248832  371293  537824]
 [ 759375 1048576 1419857 1889568 2476099]
 [3200000 4084101 5153632 6436343 7962624]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 

<ipython-input-81-135d9a1dda91>:18: RuntimeWarning: invalid value encountered in true_divide
  print(a/b)
<ipython-input-81-135d9a1dda91>:20: RuntimeWarning: divide by zero encountered in floor_divide
  print(a // b)              # The error below says we have divison by zero. But the operation gets performed
<ipython-input-81-135d9a1dda91>:21: RuntimeWarning: divide by zero encountered in remainder
  print(a % b)


In [87]:
# basic functions
a  = np.arange(25).reshape((5,5))
print(a)

print(a.max())
print(a.max(axis=1))
print(a.max(axis=0))

print(a.min())
print(a.min(axis=1))
print(a.min(axis=0))        #axis = 0  ==> vertical
                            #axis = 1  ==> Horizontal 
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
24
[ 4  9 14 19 24]
[20 21 22 23 24]
0
[ 0  5 10 15 20]
[0 1 2 3 4]
300
[50 55 60 65 70]
[ 10  35  60  85 110]
